const WEDDING_DATE = new Date('2027-05-22T14:00:00+09:00');
const toast=(m)=>{const el=document.querySelector('#toast');el.textContent=m;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
function renderCalendar(){const box=document.querySelector('#calendarDays');const y=2027,m=4;const first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();box.innerHTML='';for(let i=0;i<first;i++)box.append(document.createElement('span'));for(let d=1;d<=last;d++){const s=document.createElement('span');s.textContent=d;if(d===22)s.className='wedding';box.append(s)}}
function renderDday(){const days=Math.ceil((WEDDING_DATE-Date.now())/86400000);document.querySelector('#dday').textContent=days>0?`민준 ♥ 서연의 결혼식이 ${days}일 남았습니다.`:days===0?'오늘, 저희 결혼합니다.':`결혼한 지 ${Math.abs(days)}일 되었습니다.`}
renderCalendar();renderDday();
const gallery=document.querySelector('#gallery');for(let i=1;i<=9;i++){const path=`./assets/images/gallery-${String(i).padStart(2,'0')}.jpg`;const b=document.createElement('button');b.style.backgroundImage=`linear-gradient(#0000,#0000),url('${path}')`;b.title=`갤러리 ${i}`;b.onclick=()=>{document.querySelector('#lightboxImg').src=path;document.querySelector('#lightbox').classList.add('open')};gallery.append(b)}document.querySelector('#lightboxClose').onclick=()=>document.querySelector('#lightbox').classList.remove('open');document.querySelector('#lightbox').onclick=e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('open')};
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);toast('계좌번호를 복사했습니다.')});
document.querySelector('#copyLinkBtn').onclick=async()=>{await navigator.clipboard.writeText(location.href);toast('청첩장 링크를 복사했습니다.')};document.querySelector('#shareBtn').onclick=async()=>{if(navigator.share)await navigator.share({title:document.title,text:'민준과 서연의 결혼식에 초대합니다.',url:location.href});else{await navigator.clipboard.writeText(location.href);toast('링크를 복사했습니다.')}};
// Firebase를 설정하면 아래 동적 import가 활성화됩니다. 설정 전에는 샘플 UI로 안전하게 동작합니다.
let db=null,fb=null;try{const cfg=(await import('./firebase-config.js')).firebaseConfig;if(cfg?.apiKey&&!cfg.apiKey.includes('YOUR_')){const appMod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js');const fs=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js');db=fs.getFirestore(appMod.initializeApp(cfg));fb=fs;loadGuests()}}catch(e){console.info('Firebase not configured; guestbook runs in demo mode.')}
async function loadGuests(){if(!db)return;const {collection,getDocs,query,orderBy,limit}=fb;const snap=await getDocs(query(collection(db,'guestbook'),orderBy('createdAt','desc'),limit(30)));const list=document.querySelector('#guestList');list.innerHTML='';snap.forEach(d=>{const x=d.data();const el=document.createElement('div');el.className='guest';el.innerHTML=`<b>${escapeHtml(x.name||'익명')}</b><p>${escapeHtml(x.message||'')}</p><small>${x.createdAt?.toDate?.().toLocaleString('ko-KR')||''}</small>`;list.append(el)})}
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
document.querySelector('#guestForm').onsubmit=async e=>{e.preventDefault();if(!db){toast('Firebase 설정 후 실제 저장됩니다.');return}const f=new FormData(e.currentTarget);try{await fb.addDoc(fb.collection(db,'guestbook'),{name:f.get('name'),message:f.get('message'),password:f.get('password'),createdAt:fb.serverTimestamp()});e.currentTarget.reset();toast('축하 메시지를 남겼습니다.');await loadGuests()}catch(err){document.querySelector('#guestStatus').textContent='저장에 실패했습니다. Firestore 규칙을 확인해주세요.'}};
document.querySelector('#rsvpForm').onsubmit=async e=>{e.preventDefault();if(!db){toast('Firebase 설정 후 실제 저장됩니다.');return}const f=new FormData(e.currentTarget);await fb.addDoc(fb.collection(db,'rsvp'),{name:f.get('name'),side:f.get('side'),attendance:f.get('attendance'),count:Number(f.get('count')||1),createdAt:fb.serverTimestamp()});e.currentTarget.reset();toast('참석 여부가 전달되었습니다.')};
